/**
 * Image Generation Service
 * Handles AI image generation for book covers and character portraits
 * Uses OpenRouter's multi-modal API
 */

import { aiLogger, config, executeWithFallback, isTestEnvironment } from '@/lib/ai-core';

export interface ImageGenerationOptions {
  prompt: string;
  style?: string;
  aspectRatio?: '1:1' | '2:3' | '3:2' | '4:3' | '4:5' | '9:16' | '16:9';
  numImages?: number;
}

export interface GeneratedImage {
  url: string; // Base64 or URL
  revisedPrompt?: string;
}

/**
 * Generate an image using OpenRouter
 */
export async function generateImage(options: ImageGenerationOptions): Promise<GeneratedImage[]> {
  const { prompt, style, aspectRatio = '1:1' } = options;

  if (isTestEnvironment()) {
    return [
      {
        url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
        revisedPrompt: `Mock image of: ${prompt} in style: ${style}`,
      },
    ];
  }

  aiLogger.info('Generating image', { prompt: prompt.substring(0, 50), style, aspectRatio });

  return executeWithFallback(async provider => {
    // For image generation, we prefer models that support it.
    // We'll try to find an image-capable model for the provider or use a default one.
    let model = 'black-forest-labs/flux-1.1-pro'; // Default to a known good image model

    if (provider === 'openai') model = 'openai/dall-e-3';
    if (provider === 'google') model = 'google/gemini-2.0-flash-exp';

    const fullPrompt = style ? `${prompt} in the style of ${style}` : prompt;

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${config.openrouterApiKey}`,
        'HTTP-Referer': 'https://novelist.ai',
        'X-Title': 'Novelist.ai',
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'text',
                text: fullPrompt,
              },
            ],
          },
        ],
        modalities: ['image'],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenRouter image generation failed: ${response.status} ${errorText}`);
    }

    const data = await response.json();

    // OpenRouter's multi-modal response structure can vary by model.
    // Basic DALL-E 3 / Flux pattern via OpenRouter often returns images in the choices.

    const images: GeneratedImage[] = [];

    if (data.choices && data.choices[0]?.message?.content) {
      // Check if it's base64 in the content or a URL
      // OpenRouter often follows OpenAI format for multi-modal
      const content = data.choices[0].message.content;

      if (Array.isArray(content)) {
        for (const item of content) {
          if (item.type === 'image' || item.image_url) {
            images.push({
              url: item.image_url?.url || item.image || '',
              revisedPrompt: item.revised_prompt,
            });
          }
        }
      } else if (typeof content === 'string' && content.startsWith('data:image')) {
        images.push({ url: content });
      }
    }

    // If we didn't get images in the "standard" ways, check for other patterns
    if (images.length === 0 && data.images) {
      for (const img of data.images) {
        images.push({ url: typeof img === 'string' ? img : img.url });
      }
    }

    if (images.length === 0) {
      aiLogger.error('No images found in response', { data });
      throw new Error('No images were generated by the AI.');
    }

    return images;
  }, 'generateImage');
}

/**
 * Generate a book cover
 */
export async function generateBookCover(
  title: string,
  idea: string,
  style: string,
): Promise<string> {
  const prompt = `A professional book cover for a novel titled "${title}". 
    The book's premise is: ${idea}. 
    The style should be: ${style}. 
    High quality, cinematic lighting, book cover design. 
    NO TEXT on the image unless it's artistically integrated.`;

  const result = await generateImage({
    prompt,
    style,
    aspectRatio: '2:3',
  });

  return result[0]?.url || '';
}

/**
 * Generate a chapter illustration
 */
export async function generateChapterIllustration(
  title: string,
  summary: string,
  style: string,
): Promise<string> {
  const prompt = `An atmospheric illustration for a book chapter titled "${title}". 
    Scene summary: ${summary}. 
    The style should be: ${style}. 
    High quality, evocative digital art. 
    NO TEXT on the image.`;

  const result = await generateImage({
    prompt,
    style,
    aspectRatio: '16:9',
  });

  return result[0]?.url || '';
}

/**
 * Generate a character portrait
 */
export async function generateCharacterPortrait(
  name: string,
  description: string,
  style: string,
): Promise<string> {
  const prompt = `A detailed character portrait of ${name}. 
    Description: ${description}. 
    The style should be: ${style}. 
    Focus on facial features and personality. 
    Professional character concept art.`;

  const result = await generateImage({
    prompt,
    style,
    aspectRatio: '1:1',
  });

  return result[0]?.url || '';
}
