/**
 * Image Generation Service
 * Handles AI image generation for book covers and character portraits
 * Uses Edge Functions API for security
 */

import { aiLogger, executeWithFallback, isTestEnvironment } from '@/lib/ai-core';

export interface ImageGenerationOptions {
  prompt: string;
  style?: string;
  aspectRatio?: '1:1' | '2:3' | '3:2' | '4:3' | '4:5' | '9:16' | '16:9';
  numImages?: number;
}

export interface GeneratedImage {
  url: string;
  revisedPrompt?: string;
}

async function fetchFromEdgeAPI(
  prompt: string,
  style: string | undefined,
  provider: string,
  aspectRatio?: string,
): Promise<GeneratedImage[]> {
  const response = await fetch('/api/ai/image', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      type: 'custom',
      prompt,
      style,
      provider,
      aspectRatio,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Edge API image generation failed: ${response.status} ${errorText}`);
  }

  const data = await response.json();

  if (!data.images || !Array.isArray(data.images) || data.images.length === 0) {
    throw new Error('No images were generated by the AI.');
  }

  return data.images.map((img: { url: string; revisedPrompt?: string }) => ({
    url: img.url,
    revisedPrompt: img.revisedPrompt,
  }));
}

/**
 * Generate an image using Edge Functions API
 */
export async function generateImage(options: ImageGenerationOptions): Promise<GeneratedImage[]> {
  const { prompt, style, aspectRatio = '1:1' } = options;

  if (isTestEnvironment()) {
    return [
      {
        url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
        revisedPrompt: `Mock image of: ${prompt} in style: ${style}`,
      },
    ];
  }

  aiLogger.info('Generating image', { prompt: prompt.substring(0, 50), style, aspectRatio });

  return executeWithFallback(async provider => {
    return fetchFromEdgeAPI(prompt, style, provider, aspectRatio);
  }, 'generateImage');
}

async function fetchFromEdgeAPIForType(
  type: 'cover' | 'illustration' | 'character',
  title: string,
  description: string,
  style: string,
): Promise<string> {
  const response = await fetch('/api/ai/image', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      type,
      title,
      description,
      style,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Edge API image generation failed: ${response.status} ${errorText}`);
  }

  const data = await response.json();

  if (!data.images || !Array.isArray(data.images) || data.images.length === 0) {
    throw new Error('No images were generated by the AI.');
  }

  return data.images[0]?.url || '';
}

/**
 * Generate a book cover
 */
export async function generateBookCover(
  title: string,
  idea: string,
  style: string,
): Promise<string> {
  return fetchFromEdgeAPIForType('cover', title, idea, style);
}

/**
 * Generate a chapter illustration
 */
export async function generateChapterIllustration(
  title: string,
  summary: string,
  style: string,
): Promise<string> {
  return fetchFromEdgeAPIForType('illustration', title, summary, style);
}

/**
 * Generate a character portrait
 */
export async function generateCharacterPortrait(
  name: string,
  description: string,
  style: string,
): Promise<string> {
  return fetchFromEdgeAPIForType('character', name, description, style);
}
