import type { Project } from '@shared/types';

/**
 * Generates a standard EPUB 3.0 file from the project data.
 * @param project The project to export
 * @param enableDropCaps Whether to style the first letter of chapters
 * @returns A Promise resolving to a Blob containing the .epub file
 */
export const generateEpub = async (project: Project, enableDropCaps = false): Promise<Blob> => {
  // Dynamic import - only loads JSZip when needed (~45KB savings on initial load)
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  // 1. mimetype (must be first, uncompressed)
  zip.file('mimetype', 'application/epub+zip', { compression: 'STORE' });

  // 2. META-INF/container.xml
  zip.folder('META-INF')?.file(
    'container.xml',
    `<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
   <rootfiles>
      <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
   </rootfiles>
</container>`,
  );

  // 3. OEBPS Structure
  const oebps = zip.folder('OEBPS');
  if (!oebps) throw new Error('Failed to create OEBPS folder');

  // Styles
  const dropCapCss = enableDropCaps
    ? `
    .first-letter {
      float: left;
      font-size: 3.5em;
      line-height: 0.8;
      padding-top: 0.1em;
      padding-right: 0.1em;
      font-family: serif;
    }
  `
    : '';

  oebps.file(
    'styles.css',
    `
    body { font-family: serif; line-height: 1.6; margin: 0; padding: 1em; color: #000; background: #fff; }
    h1, h2, h3 { font-family: sans-serif; font-weight: bold; color: #333; }
    h1 { text-align: center; margin-bottom: 2em; page-break-before: always; }
    p { margin-bottom: 1em; text-indent: 1.5em; }
    .chapter-title { font-size: 2em; margin-bottom: 0.5em; }
    .cover { width: 100%; height: 100%; object-fit: cover; }
    ${dropCapCss}
  `,
  );

  // Cover Image (if exists)
  let coverFilename = '';
  if (project.coverImage != null && project.coverImage.length > 0) {
    // Assuming base64 PNG from Imagen
    const base64Data = project.coverImage.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');
    coverFilename = 'cover.png';
    oebps.file(`images/${coverFilename}`, base64Data, { base64: true });

    // Cover XHTML
    oebps.file(
      'cover.xhtml',
      `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Cover</title><link rel="stylesheet" type="text/css" href="styles.css"/></head>
<body><div style="text-align:center;height:100%;"><img src="images/${coverFilename}" alt="Cover" style="max-width:100%;height:auto;"/></div></body>
</html>`,
    );
  }

  // Title Page
  oebps.file(
    'title.xhtml',
    `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>${project.title}</title><link rel="stylesheet" type="text/css" href="styles.css"/></head>
<body>
  <div style="text-align:center; margin-top: 30%;">
    <h1>${project.title}</h1>
    <p style="font-style:italic;">${project.style}</p>
    <p style="margin-top: 4em;">Generated by Novelist.ai</p>
  </div>
</body>
</html>`,
  );

  // Chapters
  project.chapters.forEach(chapter => {
    // Markdown -> HTML
    let htmlContent = chapter.content
      .replace(/^# (.*$)/gim, '<h2>$1</h2>')
      .replace(/^## (.*$)/gim, '<h3>$1</h3>')
      .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
      .replace(/\*(.*)\*/gim, '<i>$1</i>')
      .split('\n\n')
      .map(p => `<p>${p.trim()}</p>`)
      .join('');

    // Apply Drop Cap to first paragraph if enabled
    if (enableDropCaps) {
      const firstPRegex = /<p>(.)/;
      htmlContent = htmlContent.replace(firstPRegex, '<p><span class="first-letter">$1</span>');
    }

    oebps.file(
      `chapter-${chapter.orderIndex}.xhtml`,
      `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>${chapter.title}</title><link rel="stylesheet" type="text/css" href="styles.css"/></head>
<body>
  <h1 class="chapter-title">Chapter ${chapter.orderIndex}</h1>
  <h2>${chapter.title}</h2>
  <div class="content">
    ${htmlContent}
  </div>
</body>
</html>`,
    );
  });

  // 4. Manifest (content.opf)
  const manifestItems = [
    `<item id="style" href="styles.css" media-type="text/css"/>`,
    `<item id="titlepage" href="title.xhtml" media-type="application/xhtml+xml"/>`,
    ...(coverFilename
      ? [
          `<item id="cover" href="cover.xhtml" media-type="application/xhtml+xml"/>`,
          `<item id="cover-image" href="images/${coverFilename}" media-type="image/png"/>`,
        ]
      : []),
    ...project.chapters.map(
      c =>
        `<item id="ch${c.orderIndex}" href="chapter-${c.orderIndex}.xhtml" media-type="application/xhtml+xml"/>`,
    ),
  ];

  const spineItems = [
    ...(coverFilename ? [`<itemref idref="cover"/>`] : []),
    `<itemref idref="titlepage"/>`,
    ...project.chapters.map(c => `<itemref idref="ch${c.orderIndex}"/>`),
  ];

  oebps.file(
    'content.opf',
    `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookId" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>${project.title}</dc:title>
    <dc:language>${project.language || 'en'}</dc:language>
    <dc:creator>Novelist.ai User</dc:creator>
    <meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d+Z$/, 'Z')}</meta>
    ${coverFilename ? '<meta name="cover" content="cover-image"/>' : ''}
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    ${manifestItems.join('\n    ')}
  </manifest>
  <spine toc="ncx">
    ${spineItems.join('\n    ')}
  </spine>
</package>`,
  );

  // 5. TOC (toc.ncx) - for legacy readers
  const navPoints = [
    ...(coverFilename
      ? [
          `<navPoint id="navPoint-0" playOrder="0"><navLabel><text>Cover</text></navLabel><content src="cover.xhtml"/></navPoint>`,
        ]
      : []),
    `<navPoint id="navPoint-1" playOrder="1"><navLabel><text>Title Page</text></navLabel><content src="title.xhtml"/></navPoint>`,
    ...project.chapters.map(
      (c, i) => `
    <navPoint id="navPoint-${i + 2}" playOrder="${i + 2}">
      <navLabel><text>Chapter ${c.orderIndex}: ${c.title}</text></navLabel>
      <content src="chapter-${c.orderIndex}.xhtml"/>
    </navPoint>`,
    ),
  ];

  oebps.file(
    'toc.ncx',
    `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="urn:uuid:12345"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
  <docTitle><text>${project.title}</text></docTitle>
  <navMap>
    ${navPoints.join('\n    ')}
  </navMap>
</ncx>`,
  );

  return zip.generateAsync({ type: 'blob' });
};
