import { Page } from '@playwright/test';
import { setupAISDKMock } from './mock-ai-sdk';

// Mock AI responses for E2E tests
const MOCK_RESPONSES = {
  generateOutline: {
    title: 'Test Project',
    chapters: [
      { orderIndex: 1, title: 'Chapter 1: The Beginning', summary: 'Introduction to the story' },
      { orderIndex: 2, title: 'Chapter 2: The Journey', summary: 'The adventure continues' },
      { orderIndex: 3, title: 'Chapter 3: The End', summary: 'The conclusion' },
    ],
  },
  developCharacters:
    '**Alice**: A brilliant physicist\n**Bob**: A skilled engineer\n**Charlie**: A mysterious stranger',
  buildWorld:
    '## Setting\nA futuristic space station orbiting a distant planet.\n\n## Technology\nAdvanced AI systems and FTL travel.\n\n## Society\nA diverse coalition of species working together.',
  enhancePlot:
    '## Plot Development\n1. Opening: Establish the protagonist and setting\n2. Rising Action: Conflict emerges\n3. Climax: The main conflict reaches its peak\n4. Falling Action: Consequences of the climax\n5. Resolution: The story concludes',
  polishDialogue: `# Polished Script

"Hello there," said Bob with a warm smile.

"Hi, Alice. Ready for the mission?" she replied, checking her equipment.

"Absolutely. This is going to be our greatest adventure yet."`,
  writeChapterContent: `# Chapter Title

This is a test chapter content generated by the mock AI service. It contains enough text to meet the minimum requirements for the chapter writing functionality.

The story continues with detailed narrative, character development, and plot progression that would normally be generated by the AI Gateway service.`,
  analyzeConsistency: `## Consistency Analysis

1. Character names are consistent throughout
2. Timeline is coherent
3. No major plot holes detected
4. Dialogue matches character personalities

Overall: The story shows good consistency with minor suggestions for improvement.`,
  refineChapterContent: `# Refined Chapter

This chapter has been refined with improved pacing, better dialogue, and enhanced descriptions.

## Changes Made:
- Improved paragraph flow
- Enhanced character voice
- Added sensory details
- Tightened prose`,
  continueWriting: `# Continued Chapter

The story continues from where it left off, maintaining narrative consistency and character voice.

The adventure unfolds with new challenges and developments that propel the plot forward in an engaging manner.`,
  brainstormProject: `## Brainstorming Notes

### Themes
- Friendship and teamwork
- Overcoming adversity
- Discovery and exploration

### Character Ideas
- Protagonist with unique abilities
- Loyal companion
- Formidable antagonist

### Plot Ideas
- Quest to save the world
- Journey of self-discovery
- Mystery to solve`,
  translateContent: `# Translated Content

[Content translated to the target language while maintaining meaning and tone]`,
  generateCoverImage: 'Mock: Cover image generated successfully',
  generateChapterIllustration: 'Mock: Chapter illustration generated successfully',
};

/**
 * Setup comprehensive AI Gateway mock for E2E tests
 * Intercepts AI API calls using Playwright's network interception
 */
export const setupGeminiMock = async (page: Page): Promise<void> => {
  // CRITICAL: Initialize AI SDK logger FIRST to prevent "m.log is not a function" errors
  await setupAISDKMock(page);

  console.log('[mock-ai-gateway] Gemini AI Gateway mock configured for E2E tests');

  // Intercept chat completions (character development, dialogue polish, etc.)
  await page.route('**/v1/chat/completions', async route => {
    // Respond immediately with no artificial delay for fast test execution
    const request = route.request();
    const postData = request.postDataJSON();
    const userMessage = postData?.messages?.[postData.messages.length - 1]?.content || '';

    let mockContent = MOCK_RESPONSES.writeChapterContent;

    // Smart content matching for different AI operations
    if (
      userMessage.toLowerCase().includes('character') ||
      userMessage.toLowerCase().includes('profil')
    ) {
      mockContent = MOCK_RESPONSES.developCharacters;
    } else if (
      userMessage.toLowerCase().includes('dialogue') ||
      userMessage.toLowerCase().includes('polish')
    ) {
      mockContent = MOCK_RESPONSES.polishDialogue;
    } else if (userMessage.toLowerCase().includes('world')) {
      mockContent = MOCK_RESPONSES.buildWorld;
    } else if (userMessage.toLowerCase().includes('outline')) {
      mockContent = JSON.stringify(MOCK_RESPONSES.generateOutline);
    } else if (userMessage.toLowerCase().includes('plot')) {
      mockContent = MOCK_RESPONSES.enhancePlot;
    } else if (
      userMessage.toLowerCase().includes('draft') ||
      userMessage.toLowerCase().includes('write')
    ) {
      mockContent = MOCK_RESPONSES.writeChapterContent;
    }

    // Fulfill immediately - no delays for fast tests (<100ms target)
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        id: `chatcmpl-mock-${Date.now()}`,
        object: 'chat.completion',
        created: Math.floor(Date.now() / 1000),
        model: 'mistral-medium-latest',
        choices: [
          {
            index: 0,
            message: {
              role: 'assistant',
              content: mockContent,
            },
            finish_reason: 'stop',
          },
        ],
        usage: {
          prompt_tokens: 50,
          completion_tokens: 200,
          total_tokens: 250,
        },
      }),
    });
  });

  // Intercept image generation (cover generator) - immediate response
  await page.route('**/v1/images/generations', async route => {
    // Use 1x1 transparent PNG for fast mock image
    const transparentPNG =
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

    // Fulfill immediately - no delays
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        created: Math.floor(Date.now() / 1000),
        data: [
          {
            url: transparentPNG,
          },
        ],
      }),
    });
  });

  // Intercept brainstorm API endpoints
  await page.route('**/api/ai/brainstorm', async route => {
    const request = route.request();
    const postData = request.postDataJSON();
    const { context, field } = postData || {};

    let mockContent = 'Mock brainstorming response for testing purposes.';

    if (field === 'title') {
      mockContent = 'Test Novel Title - A Story Worth Telling';
    } else if (field === 'style') {
      mockContent = 'Literary Fiction';
    } else if (context) {
      mockContent = `Enhanced concept based on: ${context.substring(0, 100)}...`;
    }

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ text: mockContent }),
    });
  });

  // Intercept generate API endpoints
  await page.route('**/api/ai/generate', async route => {
    const request = route.request();
    const postData = request.postDataJSON();

    const mockResponse = {
      id: `gen-mock-${Date.now()}`,
      object: 'text_completion',
      created: Math.floor(Date.now() / 1000),
      model: postData?.model || 'mistral-medium-latest',
      choices: [
        {
          index: 0,
          text: 'Mocked AI generation response for testing purposes.',
          finish_reason: 'stop',
        },
      ],
      usage: {
        prompt_tokens: 25,
        completion_tokens: 100,
        total_tokens: 125,
      },
    };

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(mockResponse),
    });
  });

  // Add error simulation for testing error handling
  await page.addInitScript(() => {
    if (typeof window !== 'undefined' && !window.aiGatewayTestConfig) {
      window.aiGatewayTestConfig = {
        enableNetworkErrors: false,
        enableTimeoutErrors: false,
        mockDelay: 0,
      };
    }
  });

  console.log(
    '[mock-ai-gateway] Enhanced mock setup complete - all routes configured with error handling',
  );
};
