import { Page } from '@playwright/test';

// Mock AI responses for E2E tests
const MOCK_RESPONSES = {
  generateOutline: {
    title: 'Test Project',
    chapters: [
      { orderIndex: 1, title: 'Chapter 1: The Beginning', summary: 'Introduction to the story' },
      { orderIndex: 2, title: 'Chapter 2: The Journey', summary: 'The adventure continues' },
      { orderIndex: 3, title: 'Chapter 3: The End', summary: 'The conclusion' },
    ],
  },
  developCharacters:
    '**Alice**: A brilliant physicist\n**Bob**: A skilled engineer\n**Charlie**: A mysterious stranger',
  buildWorld:
    '## Setting\nA futuristic space station orbiting a distant planet.\n\n## Technology\nAdvanced AI systems and FTL travel.\n\n## Society\nA diverse coalition of species working together.',
  enhancePlot:
    '## Plot Development\n1. Opening: Establish the protagonist and setting\n2. Rising Action: Conflict emerges\n3. Climax: The main conflict reaches its peak\n4. Falling Action: Consequences of the climax\n5. Resolution: The story concludes',
  polishDialogue: `# Polished Script

"Hello there," said Bob with a warm smile.

"Hi, Alice. Ready for the mission?" she replied, checking her equipment.

"Absolutely. This is going to be our greatest adventure yet."`,
  writeChapterContent: `# Chapter Title

This is a test chapter content generated by the mock AI service. It contains enough text to meet the minimum requirements for the chapter writing functionality.

The story continues with detailed narrative, character development, and plot progression that would normally be generated by the AI Gateway service.`,
  analyzeConsistency: `## Consistency Analysis

1. Character names are consistent throughout
2. Timeline is coherent
3. No major plot holes detected
4. Dialogue matches character personalities

Overall: The story shows good consistency with minor suggestions for improvement.`,
  refineChapterContent: `# Refined Chapter

This chapter has been refined with improved pacing, better dialogue, and enhanced descriptions.

## Changes Made:
- Improved paragraph flow
- Enhanced character voice
- Added sensory details
- Tightened prose`,
  continueWriting: `# Continued Chapter

The story continues from where it left off, maintaining narrative consistency and character voice.

The adventure unfolds with new challenges and developments that propel the plot forward in an engaging manner.`,
  brainstormProject: `## Brainstorming Notes

### Themes
- Friendship and teamwork
- Overcoming adversity
- Discovery and exploration

### Character Ideas
- Protagonist with unique abilities
- Loyal companion
- Formidable antagonist

### Plot Ideas
- Quest to save the world
- Journey of self-discovery
- Mystery to solve`,
  translateContent: `# Translated Content

[Content translated to the target language while maintaining meaning and tone]`,
  generateCoverImage: 'Mock: Cover image generated successfully',
  generateChapterIllustration: 'Mock: Chapter illustration generated successfully',
};

/**
 * Setup comprehensive AI Gateway mock for E2E tests
 * Intercepts AI SDK calls and returns mock responses
 */
export const setupGeminiMock = async (_page: Page): Promise<void> => {
  // Inject mock responses into the page context
  await _page.addInitScript(() => {
    // Override the AI service functions to return mock data in test environment
    const isTestEnv = typeof window !== 'undefined' && window.location.hostname === 'localhost';

    if (isTestEnv) {
      // Mock AI Gateway responses by patching the global fetch if needed
      console.log('[Mock AI Gateway] Test environment detected, AI calls will be mocked');

      // Store mock data in window for access by the app
      (window as any).__MOCK_AI_RESPONSES__ = {
        generateOutline: () => Promise.resolve(MOCK_RESPONSES.generateOutline),
        developCharacters: () => Promise.resolve(MOCK_RESPONSES.developCharacters),
        buildWorld: () => Promise.resolve(MOCK_RESPONSES.buildWorld),
        enhancePlot: () => Promise.resolve(MOCK_RESPONSES.enhancePlot),
        polishDialogue: () => Promise.resolve(MOCK_RESPONSES.polishDialogue),
        writeChapterContent: () => Promise.resolve(MOCK_RESPONSES.writeChapterContent),
        analyzeConsistency: () => Promise.resolve(MOCK_RESPONSES.analyzeConsistency),
        refineChapterContent: () => Promise.resolve(MOCK_RESPONSES.refineChapterContent),
        continueWriting: () => Promise.resolve(MOCK_RESPONSES.continueWriting),
        brainstormProject: () => Promise.resolve(MOCK_RESPONSES.brainstormProject),
        translateContent: () => Promise.resolve(MOCK_RESPONSES.translateContent),
        generateCoverImage: () => Promise.resolve(MOCK_RESPONSES.generateCoverImage),
        generateChapterIllustration: () =>
          Promise.resolve(MOCK_RESPONSES.generateChapterIllustration),
      };
    }
  });

  console.log('Gemini AI Gateway mock configured for E2E tests');
};
